language: bash

sudo: required

services:
- docker

env:
  global:
    - secure: "Y6OAcmmCXZu73jie9vvr3fZfl1eDfWrlb1U15v2x+JumiYdnZdHkZkWnYaBiYBkoKROf4TzMjhAlbJChB1UgfSil3jtSHTn4Q4QKmpI7+CMadani05LwWoN38HcjRWkFp6VWMaRJtbsr0Bo2xn3hucIKRw1GbNbyJ61mk8GVH5LEn1kkK0F1EEBiKk6Wbvwh8nfd1eUavi8KKjgDaUQIB/VuJvj12aoUBeU/38IAwJD8eBlNb0BXvByZUjxuyazQuXEOii9HRbp4QzinTf/Sfg/hPgSihD02kosIyFk5baYdldNmviR/xwx36g8SwOb4yU3Cz/6qLQl5w2y0yFDIONxZNQ6XB9d++0Ra8Kw9I7LeLgKKs/sI4Si2cWfA0okoI5XQHTRQO9FvDqZc5FDuQxqSDMa/9BZCLC33vDURXanJR9fMIXHyilW/6z1RTUDSvw25RtR0LpfJdCangDPwEMCAZNjRhAnRhxUC7TP2qNCb70SbSsWS4rgmruAYW7KCGJyewZZ8VB0PAZQabTaNV93nlLfr+evy5IXBn0ep2qQf/NPqsK/hwTA+F/cafJkPtdtHmffu1Kjff0ICtlk4dsSmzkPs7I0bL8XcekE8Gr9ZmRl1GbRnb9gG/XT7PMjtW4Mc4lSr6voTOPiPBCT73sshbyRyR42KyehFF1ajrBI="
    - secure: "qjsmNVW3bPZdUs5wMNhDbXsVvJCrWwNY/1Um2ue7Q2eKStMG9YwMOln+nWUG6VIiu/FwHMWkHn6zvHDkJTsZndXr8Hk8Y5ALXH7I26UOhFvriHbHbnKAIeW0jKqLOcyZBUgFrx4FAHBpv6s9jeO++pCT0OUsVZFBz7b/LmFR9y9TDxQiXKobUWf6lRMTdrvK29r7HgNRyoms2drU0yGFAlzcEjm9p89he6Am28G/j2OfGA1tnt76XsKMAwHcD2EP6DPjYoHo/dK6/dlVeHTBgGjwhEnx5wK6xakvy2D99iFDO5MkREfBfK2VjVIidq62fTcOmMUWSiWpewmbSpCSGcAh0fBLDuS6VvK/4BvrB4kXTQ6HIbP+eBcpt3mVOhhbkHxDW2n3tQ95LR/3Av1AUwuag7C7zBauUpprQMvpY95tU7ieQWshMRXkHG6ue8I5kFh2ny33QwGjMJbHVVR46TnHy5Q7Snkz69hKGxpiJVM2WOxrXOdJYNfM9ihf6ui/t1Hz262nsvBg8E4toTBxo4l5fn1Z3MCUys/P8/ao6149gBavS5mFbU9wWU9B5OUClGbdQUAsJkQYxbpnkEeVnqBDythDz6TvfYIrBLySVlJ6zQfigmTnqiGvLmmEXnSaniaIXelNC8i1LApe1nKpFCk7ppKwz6ozDfqR5GBurIc="
    - secure: "VucyJCVl2hzVRBr0TDnrbslhTHOdgGYJKCuTBfyaSXKYgrW7t/Y54+DHu/sAh6JsoNxd4PIpbKvt4puOrnDMkg+RrVu2QUxktc/wJZULzSIZZSrTN6wQyoHLynIfPhWU7PNsFMNL+eJ5CR7Qz+KLFCNAEbyNp3D4amMwNOUu+zA2X/vpmElOE5je8v5BOwflqnJUHFVG8DzFadaQIxjjdn+VYRIHo37Dhs0G+DgwN0fufP3cf6d0ZSGKN5TAIUxJJ2ev5mfxyMYhlRNnO9lzLZ1RsE9HPzTtp7dm4iwW5gPRgBtHkYhpXdToD9NBUXW76eEPyfwB3Ug/EQmAkdKgOqKfoJehFMZlC1Duz1IU3ICHslLObPHT7U/PPMu6Tfx/lOjY0N1xUtdv4v+O+6VuMFojMyYsEqoSuA52/HP7ZnUOmo9LWuA7gUoOKOnQWUO+NYOh8F9ghBWxpZOAWxrNwzO6MVV6Y6NLKdLeG+UnJIfo/H/+s9UkcXqPhIINaitKD465rJ5t9h4j+GXxDQdXnz+EuYtmB1BYhRYw9qX51eJbdw/TE02OTwQot4th3KqdXyxP9c2837Rlkkc4gjWHRwTdAN68VsXg36E4gQJ1hITPBCvwbf1n8FGDlsSHW0SRADF52lFJeBCmbohgEveSL1sfx2nS9Ru79yD4+2Thi+U="
    - PROJECT="java"
    - REPOSITORY="encodeering"
    - BRANCH="$TRAVIS_BRANCH"
    - COMMIT="238cc35696423794b1951fc63d4cc9ffb8ca9685"
  matrix:
    - BASE=debian ARCH=armhf VERSION=7-jre VERSIONPIN=7u95-2.6.4-1~deb8u1  VARIANT=openjdk
    - BASE=debian ARCH=armhf VERSION=7-jdk VERSIONPIN=7u95-2.6.4-1~deb8u1  VARIANT=openjdk
    - BASE=debian ARCH=armhf VERSION=8-jre VERSIONPIN=8u91-b14-1~bpo8+1    VARIANT=openjdk
    - BASE=debian ARCH=armhf VERSION=8-jdk VERSIONPIN=8u91-b14-1~bpo8+1    VARIANT=openjdk
    - BASE=debian ARCH=armhf VERSION=8-jdk VARIANT=oracle   VERSIONSHA=2cca3c6ffcc016ae531802202562ef20630500e134838017a6e91daac2dbb339
      DOWNLOAD=http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-arm32-vfp-hflt.tar.gz
      LEGAL=http://www.oracle.com/technetwork/java/javase/terms/license/index.html

    - BASE=debian ARCH=amd64 VERSION=7-jre VERSIONPIN=7u101-2.6.6-1~deb8u1 VARIANT=openjdk
    - BASE=debian ARCH=amd64 VERSION=7-jdk VERSIONPIN=7u101-2.6.6-1~deb8u1 VARIANT=openjdk
    - BASE=debian ARCH=amd64 VERSION=8-jre VERSIONPIN=8u91-b14-1~bpo8+1    VARIANT=openjdk
    - BASE=debian ARCH=amd64 VERSION=8-jdk VERSIONPIN=8u91-b14-1~bpo8+1    VARIANT=openjdk
    - BASE=debian ARCH=amd64 VERSION=8-jdk VARIANT=oracle   VERSIONSHA=c78200ce409367b296ec39be4427f020e2c585470c4eed01021feada576f027f
      DOWNLOAD=http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
      LEGAL=http://www.oracle.com/technetwork/java/javase/terms/license/index.html

install:
- bash <(curl https://raw.githubusercontent.com/encodeering/docker-ci/master/install.sh) 0.1.5

before_script:
- sudo -E bash ./module.sh "." "./setup.sh" "https://github.com/docker-library/openjdk.git" "modules/$PROJECT" "$COMMIT"

script:
- sudo -E bash ./module.sh "modules" "./build.sh"

after_script:
- docker images

deploy:
  script: sudo -E bash ./module.sh "." "./release.sh"
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
