diff --git a/8-jre/Dockerfile b/8-jre/Dockerfile
index a6f97ec..124d0cc 100644
--- a/8-jre/Dockerfile
+++ b/8-jre/Dockerfile
@@ -39,2 +39,2 @@ ENV JAVA_HOME /docker-java-home/jre
-ENV JAVA_VERSION 8u131
-ENV JAVA_DEBIAN_VERSION 8u131-b11-1~bpo8+1
+ENV JAVA_VERSION 8u131
+ENV JAVA_DEBIAN_VERSION 8u131-b11-1~bpo8+1
