diff --git a/8-jdk/alpine/Dockerfile b/8-jdk/alpine/Dockerfile
index 20a8981..71da8df 100644
--- a/8-jdk/alpine/Dockerfile
+++ b/8-jdk/alpine/Dockerfile
@@ -29,2 +29,2 @@ ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openj
-ENV JAVA_VERSION 8u131
-ENV JAVA_ALPINE_VERSION 8.131.11-r2
+ENV JAVA_VERSION 8u151
+ENV JAVA_ALPINE_VERSION 8.151.12-r0
