diff --git a/8/jdk/Dockerfile b/8/jdk/Dockerfile
index 60a3346..ca231d6
--- a/8/jdk/Dockerfile
+++ b/8/jdk/Dockerfile
@@ -43 +43 @@ ENV JAVA_VERSION 8u212
-ENV JAVA_DEBIAN_VERSION 8u212-b01-1~deb9u1
+ENV JAVA_DEBIAN_VERSION 8u212-b03-2~deb9u1
