diff --git a/7-jre/Dockerfile b/7-jre/Dockerfile
index d855651..6083577 100644
--- a/7-jre/Dockerfile
+++ b/7-jre/Dockerfile
@@ -30,7 +30,8 @@ RUN { \
 	} > /usr/local/bin/docker-java-home \
 	&& chmod +x /usr/local/bin/docker-java-home
 
-ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64/jre
+ARG ARCH
+ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-${ARCH}/jre
 
 ENV JAVA_VERSION 7u101
 ENV JAVA_DEBIAN_VERSION 7u101-2.6.6-1~deb8u1
