diff --git a/8-jdk/Dockerfile b/8-jdk/Dockerfile
index 3bb7878..4313267 100644
--- a/8-jdk/Dockerfile
+++ b/8-jdk/Dockerfile
@@ -35 +35,2 @@ RUN { \
-ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
+ARG ARCH
+ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-${ARCH}
@@ -37,2 +38,2 @@ ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
-ENV JAVA_VERSION 8u91
-ENV JAVA_DEBIAN_VERSION 8u91-b14-1~bpo8+1
+ARG JAVA_VERSION=8u91
+ARG JAVA_DEBIAN_VERSION
