diff --git a/7-jre/Dockerfile b/7-jre/Dockerfile
index 2686968..8374981 100644
--- a/7-jre/Dockerfile
+++ b/7-jre/Dockerfile
@@ -37,2 +37,2 @@ ENV JAVA_HOME /docker-java-home/jre
-ENV JAVA_VERSION 7u131
-ENV JAVA_DEBIAN_VERSION 7u131-2.6.9-2~deb8u1
+ENV JAVA_VERSION 7u151
+ENV JAVA_DEBIAN_VERSION 7u151-2.6.11-2~deb8u1
