diff --git a/8-jre/Dockerfile b/8-jre/Dockerfile
index 8a98caa..1f22806 100644
--- a/8-jre/Dockerfile
+++ b/8-jre/Dockerfile
@@ -35 +35,2 @@ RUN { \
-ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/jre
+ARG ARCH
+ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-${ARCH}/jre
@@ -37,2 +38,2 @@ ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/jre
-ENV JAVA_VERSION 8u91
-ENV JAVA_DEBIAN_VERSION 8u91-b14-1~bpo8+1
+ARG JAVA_VERSION=8u91
+ARG JAVA_DEBIAN_VERSION
