diff --git a/8-jre/Dockerfile b/8-jre/Dockerfile
index 70e3a0e..a653ff1 100644
--- a/8-jre/Dockerfile
+++ b/8-jre/Dockerfile
@@ -32,7 +32,8 @@ RUN { \
 	} > /usr/local/bin/docker-java-home \
 	&& chmod +x /usr/local/bin/docker-java-home
 
-ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/jre
+ARG ARCH
+ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-${ARCH}/jre
 
 ENV JAVA_VERSION 8u72
 ENV JAVA_DEBIAN_VERSION 8u72-b15-1~bpo8+1
